namespace GIGA.ITRI.SA6200.UI.Process.FilmLoading
{
    public enum FilmLoadStep
    {
        START,

        MOT_GANTRY_ENABLE_ENTER,
        MOT_GANTRY_ENABLE_POLLING,

        UV_LAMP_OFF_ENTER,
        UV_LAMP_OFF_POLLING,

        REG_SETTING_ENTER,
        REG_SETTING_POLLING,

        GAP_PRESS_UP_ENTER,
        GAP_PRESS_UP_POLLING,

        UV_CYLINDER_UP_ENTER,
        UV_CYLINDER_UP_POLLING,

        LIFT_PIN_DOWN_ENTER,
        LIFT_PIN_DOWN_POLLING,

        FILM_CLAMP_DOWN_ENTER,
        FILM_CLAMP_DOWN_POLLING,

        MOT_GAP_HOME_MOVE_ENTER,
        MOT_GAP_HOME_MOVE_POLLING,

        MOT_READY_MOVE_ENTER,
        MOT_READY_MOVE_POLLING,

        MOT_HOME_MOVE_ENTER,
        MOT_HOME_MOVE_POLLING,

        MOT_FILM_LOADING_MOVE_ENTER,
        MOT_FILM_LOADING_MOVE_POLLING,

        GAP_PRESS_DOWN_ENTER,
        GAP_PRESS_DOWN_POLLING,

        MOT_GAP_PRESS_MOVE_ENTER,
        MOT_GAP_PRESS_MOVE_POLLING,

        END,
    }
}
